### Random Forest

In [2]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, f1_score, accuracy_score

# ---------------------------
# Load Splits
# ---------------------------
train_df = pd.read_csv(r"C:\Users\HP\Desktop\Projects\ML Project\E4\train_split.csv")
val_df   = pd.read_csv(r"C:\Users\HP\Desktop\Projects\ML Project\E4\val_split.csv")
test_df  = pd.read_csv(r"C:\Users\HP\Desktop\Projects\ML Project\E4\test_split.csv")

# ---------------------------
# Features & Target
# ---------------------------
features = ['bvp_mean', 'bvp_std', 'hr_mean', 'hr_std',
            'ibi_std', 'bvp_filtered', 'acc_mag', 'acc_mag_smooth']
target = 'stress_level'

X_train = train_df[features]
y_train = train_df[target]

X_val   = val_df[features]
y_val   = val_df[target]

# ✅ Test has features only (no labels)
X_test  = test_df[features]

# ---------------------------
# Scaling
# ---------------------------
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled   = scaler.transform(X_val)
X_test_scaled  = scaler.transform(X_test)

# ---------------------------
# Model Definition
# ---------------------------
rf = RandomForestClassifier(
    n_estimators=2000,
    max_depth=6,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)

# ---------------------------
# Train Model
# ---------------------------
rf.fit(X_train_scaled, y_train)

# ---------------------------
# Validation Evaluation
# ---------------------------
y_val_pred = rf.predict(X_val_scaled)

print("\n📊 Validation Results")
print(classification_report(y_val, y_val_pred))
print("Confusion Matrix:\n", confusion_matrix(y_val, y_val_pred))
print(f"Accuracy: {accuracy_score(y_val, y_val_pred):.4f}")
print(f"Weighted F1 Score: {f1_score(y_val, y_val_pred, average='weighted'):.4f}")

# ---------------------------
# ✅ Test Predictions (NO accuracy possible)
# ---------------------------
test_predictions = rf.predict(X_test_scaled)

test_output = test_df.copy()
test_output["Predicted_Stress_Level"] = test_predictions

test_output.to_csv("test_predictions_E4_RF.csv", index=False)
print("\n✅ Test predictions generated")


📊 Validation Results
              precision    recall  f1-score   support

        High       0.85      0.64      0.73      6452
         Low       0.13      0.69      0.21       353
      Medium       0.70      0.70      0.70      4787

    accuracy                           0.67     11592
   macro avg       0.56      0.68      0.55     11592
weighted avg       0.76      0.67      0.70     11592

Confusion Matrix:
 [[4144  883 1425]
 [  73  244   36]
 [ 653  802 3332]]
Accuracy: 0.6660
Weighted F1 Score: 0.7012

✅ Test predictions generated


### Logistic Regression

In [3]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer
from sklearn.metrics import classification_report, confusion_matrix, f1_score, accuracy_score

# ---------------------------
# Load Splits
# ---------------------------
train_df = pd.read_csv(r"C:\Users\HP\Desktop\Projects\ML Project\E4\train_split.csv")
val_df   = pd.read_csv(r"C:\Users\HP\Desktop\Projects\ML Project\E4\val_split.csv")
test_df  = pd.read_csv(r"C:\Users\HP\Desktop\Projects\ML Project\E4\test_split.csv")

# ---------------------------
# Features & Target
# ---------------------------
features = ['bvp_mean', 'bvp_std', 'hr_mean', 'hr_std',
            'ibi_std', 'bvp_filtered', 'acc_mag', 'acc_mag_smooth']
target = 'stress_level'

X_train = train_df[features]
y_train = train_df[target]

X_val   = val_df[features]
y_val   = val_df[target]

X_test  = test_df[features]

# ---------------------------
# ✅ Impute Missing Values
# ---------------------------
imputer = SimpleImputer(strategy="mean")

X_train_imp = imputer.fit_transform(X_train)
X_val_imp   = imputer.transform(X_val)
X_test_imp  = imputer.transform(X_test)

# ---------------------------
# ✅ Scaling
# ---------------------------
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train_imp)
X_val_scaled   = scaler.transform(X_val_imp)
X_test_scaled  = scaler.transform(X_test_imp)

# ---------------------------
# ✅ Logistic Regression
# ---------------------------
model = LogisticRegression(
    multi_class="multinomial",
    class_weight="balanced",
    max_iter=2000,
    solver="lbfgs"
)

model.fit(X_train_scaled, y_train)

# ---------------------------
# Validation Evaluation
# ---------------------------
y_val_pred = model.predict(X_val_scaled)

print("\n📊 Logistic Regression - Validation Results")
print(classification_report(y_val, y_val_pred))
print("Confusion Matrix:\n", confusion_matrix(y_val, y_val_pred))
print(f"Accuracy: {accuracy_score(y_val, y_val_pred):.4f}")
print(f"Weighted F1 Score: {f1_score(y_val, y_val_pred, average='weighted'):.4f}")

# ---------------------------
# Test Predictions
# ---------------------------
test_predictions = model.predict(X_test_scaled)

test_output = test_df.copy()
test_output["Predicted_Stress_Level"] = test_predictions
test_output.to_csv("test_predictions_E4_LogReg.csv", index=False)

print("\n✅ Test predictions generated (with imputation)")

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(



📊 Logistic Regression - Validation Results
              precision    recall  f1-score   support

        High       0.80      0.71      0.75      6452
         Low       0.17      0.81      0.28       353
      Medium       0.69      0.59      0.64      4787

    accuracy                           0.66     11592
   macro avg       0.55      0.71      0.55     11592
weighted avg       0.73      0.66      0.69     11592

Confusion Matrix:
 [[4582  653 1217]
 [   7  287   59]
 [1156  792 2839]]
Accuracy: 0.6649
Weighted F1 Score: 0.6900

✅ Test predictions generated (with imputation)


### Decision Tree Classifier

In [4]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.impute import SimpleImputer
from sklearn.metrics import classification_report, confusion_matrix, f1_score, accuracy_score

# Load
train_df = pd.read_csv(r"C:\Users\HP\Desktop\Projects\ML Project\E4\train_split.csv")
val_df   = pd.read_csv(r"C:\Users\HP\Desktop\Projects\ML Project\E4\val_split.csv")
test_df  = pd.read_csv(r"C:\Users\HP\Desktop\Projects\ML Project\E4\test_split.csv")

features = ['bvp_mean', 'bvp_std', 'hr_mean', 'hr_std',
            'ibi_std', 'bvp_filtered', 'acc_mag', 'acc_mag_smooth']
target = 'stress_level'

X_train = train_df[features]
y_train = train_df[target]

X_val = val_df[features]
y_val = val_df[target]

X_test = test_df[features]

# Impute
imputer = SimpleImputer(strategy="mean")
X_train_imp = imputer.fit_transform(X_train)
X_val_imp   = imputer.transform(X_val)
X_test_imp  = imputer.transform(X_test)

# Model
model = DecisionTreeClassifier(
    max_depth=6,
    class_weight="balanced",
    random_state=42
)

model.fit(X_train_imp, y_train)

# Validation
y_val_pred = model.predict(X_val_imp)

print("\n📊 Decision Tree - Validation Results")
print(classification_report(y_val, y_val_pred))
print("Confusion Matrix:\n", confusion_matrix(y_val, y_val_pred))
print(f"Accuracy: {accuracy_score(y_val, y_val_pred):.4f}")
print(f"Weighted F1 Score: {f1_score(y_val, y_val_pred, average='weighted'):.4f}")

# Test
test_pred = model.predict(X_test_imp)
test_output = test_df.copy()
test_output["Predicted_Stress_Level"] = test_pred
test_output.to_csv("test_predictions_E4_DecisionTree.csv", index=False)

print("\n✅ Test predictions saved")


📊 Decision Tree - Validation Results
              precision    recall  f1-score   support

        High       0.93      0.60      0.73      6452
         Low       0.15      0.75      0.25       353
      Medium       0.65      0.77      0.71      4787

    accuracy                           0.68     11592
   macro avg       0.58      0.71      0.56     11592
weighted avg       0.79      0.68      0.71     11592

Confusion Matrix:
 [[3878  700 1874]
 [   9  266   78]
 [ 286  796 3705]]
Accuracy: 0.6771
Weighted F1 Score: 0.7070

✅ Test predictions saved


### XGBoost Classifier

In [5]:
import pandas as pd
import xgboost as xgb
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix, f1_score, accuracy_score

# ---------------------------
# Load Data
# ---------------------------
train_df = pd.read_csv(r"C:\Users\HP\Desktop\Projects\ML Project\E4\train_split.csv")
val_df   = pd.read_csv(r"C:\Users\HP\Desktop\Projects\ML Project\E4\val_split.csv")
test_df  = pd.read_csv(r"C:\Users\HP\Desktop\Projects\ML Project\E4\test_split.csv")

# ---------------------------
# Features & Target
# ---------------------------
features = ['bvp_mean', 'bvp_std', 'hr_mean', 'hr_std',
            'ibi_std', 'bvp_filtered', 'acc_mag', 'acc_mag_smooth']
target = 'stress_level'

X_train = train_df[features]
y_train = train_df[target]

X_val = val_df[features]
y_val = val_df[target]

X_test = test_df[features]

# ---------------------------
# ✅ Encode String Labels → Numbers
# ---------------------------
le = LabelEncoder()
y_train_enc = le.fit_transform(y_train)   # ['High','Low','Medium'] → [0,1,2]
y_val_enc   = le.transform(y_val)

# ---------------------------
# Model
# ---------------------------
model = xgb.XGBClassifier(
    n_estimators=2000,
    learning_rate=0.005,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="multi:softprob",
    eval_metric="mlogloss",
    num_class=3,
    tree_method="hist",
    random_state=42
)

model.fit(X_train, y_train_enc)

# ---------------------------
# Validation Predictions
# ---------------------------
y_val_pred_enc = model.predict(X_val)
y_val_pred = le.inverse_transform(y_val_pred_enc)

print("\n📊 XGBoost - Validation Results")
print(classification_report(y_val, y_val_pred))
print("Confusion Matrix:\n", confusion_matrix(y_val, y_val_pred))
print(f"Accuracy: {accuracy_score(y_val, y_val_pred):.4f}")
print(f"Weighted F1 Score: {f1_score(y_val, y_val_pred, average='weighted'):.4f}")

# ---------------------------
# Test Predictions
# ---------------------------
test_pred_enc = model.predict(X_test)
test_pred = le.inverse_transform(test_pred_enc)

test_output = test_df.copy()
test_output["Predicted_Stress_Level"] = test_pred

test_output.to_csv("test_predictions_E4_XGBoost.csv", index=False)

print("\n✅ Test predictions saved")


📊 XGBoost - Validation Results
              precision    recall  f1-score   support

        High       0.82      0.67      0.74      6452
         Low       0.14      0.03      0.04       353
      Medium       0.63      0.82      0.71      4787

    accuracy                           0.71     11592
   macro avg       0.53      0.51      0.50     11592
weighted avg       0.72      0.71      0.71     11592

Confusion Matrix:
 [[4310   27 2115]
 [ 117    9  227]
 [ 811   27 3949]]
Accuracy: 0.7133
Weighted F1 Score: 0.7062

✅ Test predictions saved


### CatBoost Classifier

In [6]:
import pandas as pd
from catboost import CatBoostClassifier
from sklearn.metrics import classification_report, confusion_matrix, f1_score, accuracy_score

# Load
train_df = pd.read_csv(r"C:\Users\HP\Desktop\Projects\ML Project\E4\train_split.csv")
val_df   = pd.read_csv(r"C:\Users\HP\Desktop\Projects\ML Project\E4\val_split.csv")
test_df  = pd.read_csv(r"C:\Users\HP\Desktop\Projects\ML Project\E4\test_split.csv")

features = ['bvp_mean', 'bvp_std', 'hr_mean', 'hr_std',
            'ibi_std', 'bvp_filtered', 'acc_mag', 'acc_mag_smooth']
target = 'stress_level'

X_train = train_df[features]
y_train = train_df[target]

X_val = val_df[features]
y_val = val_df[target]

X_test = test_df[features]

# Model
model = CatBoostClassifier(
    iterations=2000,
    depth=6,
    learning_rate=0.005,
    loss_function="MultiClass",
    random_seed=42,
    verbose=0
)

model.fit(X_train, y_train)

# Validation
y_val_pred = model.predict(X_val)

print("\n📊 CatBoost - Validation Results")
print(classification_report(y_val, y_val_pred))
print("Confusion Matrix:\n", confusion_matrix(y_val, y_val_pred))
print(f"Accuracy: {accuracy_score(y_val, y_val_pred):.4f}")
print(f"Weighted F1 Score: {f1_score(y_val, y_val_pred, average='weighted'):.4f}")

# ---------------------------
# ✅ Test Predictions
# ---------------------------
test_pred = model.predict(X_test)

# Flatten if needed (CatBoost returns 2D)
if test_pred.ndim > 1:
    test_pred = test_pred.ravel()

test_output = test_df.copy()
test_output["Predicted_Stress_Level"] = test_pred

test_output.to_csv("test_predictions_E4_CatBoost.csv", index=False)

print("\n✅ Test predictions saved")


📊 CatBoost - Validation Results
              precision    recall  f1-score   support

        High       0.83      0.67      0.74      6452
         Low       0.00      0.00      0.00       353
      Medium       0.63      0.84      0.72      4787

    accuracy                           0.72     11592
   macro avg       0.49      0.50      0.49     11592
weighted avg       0.72      0.72      0.71     11592

Confusion Matrix:
 [[4350    0 2102]
 [ 114    0  239]
 [ 775    1 4011]]
Accuracy: 0.7213
Weighted F1 Score: 0.7116

✅ Test predictions saved


### LightGBM

In [7]:
import pandas as pd
import lightgbm as lgb
from sklearn.metrics import classification_report, confusion_matrix, f1_score, accuracy_score

# Load
train_df = pd.read_csv(r"C:\Users\HP\Desktop\Projects\ML Project\E4\train_split.csv")
val_df   = pd.read_csv(r"C:\Users\HP\Desktop\Projects\ML Project\E4\val_split.csv")
test_df  = pd.read_csv(r"C:\Users\HP\Desktop\Projects\ML Project\E4\test_split.csv")

features = ['bvp_mean', 'bvp_std', 'hr_mean', 'hr_std',
            'ibi_std', 'bvp_filtered', 'acc_mag', 'acc_mag_smooth']
target = 'stress_level'

X_train = train_df[features]
y_train = train_df[target]

X_val = val_df[features]
y_val = val_df[target]

X_test = test_df[features]

# Model
model = lgb.LGBMClassifier(
    n_estimators=2000,
    max_depth=6,
    learning_rate=0.005,
    class_weight="balanced",
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    verbose=-1
)

model.fit(X_train, y_train)

# Validation
y_val_pred = model.predict(X_val)

print("\n📊 LightGBM - Validation Results")
print(classification_report(y_val, y_val_pred))
print("Confusion Matrix:\n", confusion_matrix(y_val, y_val_pred))
print(f"Accuracy: {accuracy_score(y_val, y_val_pred):.4f}")
print(f"Weighted F1 Score: {f1_score(y_val, y_val_pred, average='weighted'):.4f}")

# Test
test_pred = model.predict(X_test)
test_output = test_df.copy()
test_output["Predicted_Stress_Level"] = test_pred
test_output.to_csv("test_predictions_E4_LightGBM.csv", index=False)

print("\n✅ Test predictions saved")


📊 LightGBM - Validation Results
              precision    recall  f1-score   support

        High       0.83      0.65      0.73      6452
         Low       0.15      0.48      0.23       353
      Medium       0.65      0.75      0.70      4787

    accuracy                           0.68     11592
   macro avg       0.55      0.62      0.55     11592
weighted avg       0.74      0.68      0.70     11592

Confusion Matrix:
 [[4162  475 1815]
 [ 106  168   79]
 [ 748  457 3582]]
Accuracy: 0.6825
Weighted F1 Score: 0.6993

✅ Test predictions saved


### MLP

In [8]:
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, f1_score, accuracy_score

# Load
train_df = pd.read_csv(r"C:\Users\HP\Desktop\Projects\ML Project\E4\train_split.csv")
val_df   = pd.read_csv(r"C:\Users\HP\Desktop\Projects\ML Project\E4\val_split.csv")
test_df  = pd.read_csv(r"C:\Users\HP\Desktop\Projects\ML Project\E4\test_split.csv")

features = ['bvp_mean', 'bvp_std', 'hr_mean', 'hr_std',
            'ibi_std', 'bvp_filtered', 'acc_mag', 'acc_mag_smooth']
target = 'stress_level'

X_train = train_df[features]
y_train = train_df[target]

X_val = val_df[features]
y_val = val_df[target]

X_test = test_df[features]

# Imputation
imputer = SimpleImputer(strategy="mean")
X_train_imp = imputer.fit_transform(X_train)
X_val_imp   = imputer.transform(X_val)
X_test_imp  = imputer.transform(X_test)

# Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_imp)
X_val_scaled   = scaler.transform(X_val_imp)
X_test_scaled  = scaler.transform(X_test_imp)

# Model
model = MLPClassifier(
    hidden_layer_sizes=(128, 64),
    activation="relu",
    solver="adam",
    max_iter=2000,
    random_state=42
)

model.fit(X_train_scaled, y_train)

# Validation
y_val_pred = model.predict(X_val_scaled)

print("\n📊 MLP Neural Network - Validation Results")
print(classification_report(y_val, y_val_pred))
print("Confusion Matrix:\n", confusion_matrix(y_val, y_val_pred))
print(f"Accuracy: {accuracy_score(y_val, y_val_pred):.4f}")
print(f"Weighted F1 Score: {f1_score(y_val, y_val_pred, average='weighted'):.4f}")

# Test
test_pred = model.predict(X_test_scaled)
test_output = test_df.copy()
test_output["Predicted_Stress_Level"] = test_pred
test_output.to_csv("test_predictions_E4_MLP.csv", index=False)

print("\n✅ Test predictions saved")


📊 MLP Neural Network - Validation Results
              precision    recall  f1-score   support

        High       0.69      0.74      0.71      6452
         Low       0.07      0.04      0.05       353
      Medium       0.60      0.57      0.58      4787

    accuracy                           0.65     11592
   macro avg       0.45      0.45      0.45     11592
weighted avg       0.63      0.65      0.64     11592

Confusion Matrix:
 [[4769   86 1597]
 [ 134   13  206]
 [2001   80 2706]]
Accuracy: 0.6460
Weighted F1 Score: 0.6394

✅ Test predictions saved


### Deep MLP

In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, f1_score, accuracy_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.utils import to_categorical

# ---------------------------
# Load Data
# ---------------------------
train_df = pd.read_csv(r"C:\Users\HP\Desktop\Projects\ML Project\E4\train_split.csv")
val_df   = pd.read_csv(r"C:\Users\HP\Desktop\Projects\ML Project\E4\val_split.csv")
test_df  = pd.read_csv(r"C:\Users\HP\Desktop\Projects\ML Project\E4\test_split.csv")

features = ['bvp_mean', 'bvp_std', 'hr_mean', 'hr_std',
            'ibi_std', 'bvp_filtered', 'acc_mag', 'acc_mag_smooth']
target = 'stress_level'

X_train = train_df[features]
y_train = train_df[target]

X_val = val_df[features]
y_val = val_df[target]

X_test = test_df[features]

# ---------------------------
# Encode labels
# ---------------------------
label_map = {"Low": 0, "Medium": 1, "High": 2}
inv_map = {0:"Low", 1:"Medium", 2:"High"}

y_train_enc = train_df[target].map(label_map).values
y_val_enc   = val_df[target].map(label_map).values

y_train_cat = to_categorical(y_train_enc, 3)
y_val_cat   = to_categorical(y_val_enc, 3)

# ---------------------------
# Imputation
# ---------------------------
imputer = SimpleImputer(strategy="mean")
X_train_imp = imputer.fit_transform(X_train)
X_val_imp   = imputer.transform(X_val)
X_test_imp  = imputer.transform(X_test)

# ---------------------------
# Scaling
# ---------------------------
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_imp)
X_val_scaled   = scaler.transform(X_val_imp)
X_test_scaled  = scaler.transform(X_test_imp)

# ---------------------------
# Deep MLP Model
# ---------------------------
model = Sequential([
    Dense(256, activation='relu', input_shape=(8,)),
    Dropout(0.3),
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dense(3, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# ---------------------------
# Train Model
# ---------------------------
model.fit(
    X_train_scaled, y_train_cat,
    validation_data=(X_val_scaled, y_val_cat),
    epochs=25,
    batch_size=32,
    verbose=1
)

# ---------------------------
# Validation Evaluation
# ---------------------------
val_pred_prob = model.predict(X_val_scaled)
val_pred = np.argmax(val_pred_prob, axis=1)
val_pred_labels = [inv_map[i] for i in val_pred]

print("\n📊 Deep MLP - Validation Results")
print(classification_report(y_val, val_pred_labels))
print("Confusion Matrix:\n", confusion_matrix(y_val, val_pred_labels))
print(f"Accuracy: {accuracy_score(y_val, val_pred_labels):.4f}")
print(f"Weighted F1 Score: {f1_score(y_val, val_pred_labels, average='weighted'):.4f}")

# ---------------------------
# Test Predictions
# ---------------------------
test_pred_prob = model.predict(X_test_scaled)
test_pred = np.argmax(test_pred_prob, axis=1)
test_pred_labels = [inv_map[i] for i in test_pred]

test_output = test_df.copy()
test_output["Predicted_Stress_Level"] = test_pred_labels
test_output.to_csv("test_predictions_E4_DeepMLP.csv", index=False)

print("\n✅ Test predictions saved")

Epoch 1/25


C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1788/1788 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7358 - loss: 0.5691 - val_accuracy: 0.7094 - val_loss: 0.5822
Epoch 2/25
1788/1788 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7647 - loss: 0.5036 - val_accuracy: 0.7063 - val_loss: 0.5690
Epoch 3/25
1788/1788 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7686 - loss: 0.4909 - val_accuracy: 0.7238 - val_loss: 0.5825
Epoch 4/25
1788/1788 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7733 - loss: 0.4831 - val_accuracy: 0.7190 - val_loss: 0.5726
Epoch 5/25
1788/1788 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7780 - loss: 0.4737 - val_accuracy: 0.7014 - val_loss: 0.6061
Epoch 6/25
1788/1788 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7790 - loss: 0.4727 - val_accuracy: 0.6928 - val_loss: 0.6203
Epoch 7/25
1788/1788 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.7849 - loss: 0.4626 - val_accuracy: 0.7057 - val_loss: 0.6060
Epoch 8/25
1788/1788 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7898 - loss: 0.4555 - val_accurac